fix missing file path option in newer rollup versions
TypeError: Cannot read property 'output' of undefined
    at Object.ongenerate (rollup-plugin-bundle-size/index.js:12:49)
    at bundle.plugins.forEach.plugin (rollup/dist/rollup.js:18689:16)
    at Array.forEach (<anonymous>)
    at Promise.resolve.then.then.rendered (rollup/dist/rollup.js:18687:22)
    at <anonymous>